### ISSUE TITLE
Exception using django 1.8

### ISSUE THREAD

**Issue by jacopsd** [django-inplaceedit/django-inplaceedit#101]
This exception appears twice when running unit tests of my project under Django 1.8.16:

** Exception occured: near "from": syntax error
/myproject/venv/lib/python2.7/site-packages/inplaceeditform/commons.py:74: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/myproject/venv/lib/python2.7/site-packages/inplaceeditform/commons.py:74: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

**Comment by dezoito** [comment]
Replace

`from django.utils.importlib import import_module`

with

`from importlib import import_module`
