### ISSUE TITLE
Add attributes to widgets

### ISSUE THREAD

**Issue by philippeluickx** [django-inplaceedit/django-inplaceedit#56]
Hey,

I am trying to add an attribute to an inplace widget.
Concrete: trying to set rows and maxlength on a textarea.

Would be awesome if we could pass that in somehow, without writing a seperate adaptor for each case.  Any ideas on how this would be feasible?

**Comment by goinnn** [comment]
Solved via js:
https://github.com/django-inplaceedit/django-inplaceedit/commit/16e928ee96a96138c16450df7fe0a089261151b7

https://github.com/django-inplaceedit/django-inplaceedit-bootstrap/commit/544b43cf73d362dd3ff0503537ca2d6dccbaf221
