### ISSUE TITLE
Display issue when entering HTML-like input

### ISSUE THREAD

**Issue by ehashman** [django-inplaceedit/django-inplaceedit#61]
The line this problem stems from appears to be

https://github.com/Yaco-Sistemas/django-inplaceedit/blob/d22ff7412e52bc964001b1e69e9957bc5343e2c5/inplaceeditform/static/js/jquery.inplaceeditform.js#L346

Here are a few examples of new values that cause the unexpected behaviour:

```
1. <foo>
2. Dog tags <dog
3. </foo>
```

On async reload the DOM breaks because the '<' character is inserted directly into the page without escaping; when my browser (Firefox 30) attempts to fix the broken tags, the `inplaceeditform` tag gets eaten or modified, which makes changing the field value impossible. A page reload "fixes" the problem by rewriting the DOM correctly, since django properly escapes the field values, so this problem is likely client-side only.

**Comment by goinnn** [comment]
I think it is a jQuery bug. For example it works "Dog tags < dog" but it does not work "Dog tags <dog". But if you give me a solution I will accept sure :-)
