### ISSUE TITLE
Adding or editing foreign key values from inline dropdowns

### ISSUE THREAD

**Issue by moaxey** [django-inplaceedit/django-inplaceedit#70]
I kind of hope this is a stupid question, but can't seem to find any documentation/examples.

It great being able to click and choose a set value from a dropdown. I'd like to be able to have something equivalent to the django-admin 'plus' symbol appear with the other edit icons that allows you to add or edit an option in the select in a popup window.

Am I just missing a configuration to enable this, or is this a feature that would be useful to others?

**Comment by goinnn** [comment]
I'm sorry I don't know  django-admin 'plus'
