### ISSUE TITLE
dynamic content not working

### ISSUE THREAD

**Issue by ajendrex** [django-inplaceedit/django-inplaceedit#71]
Hello,

I'm using [bootstrap-table](http://bootstrap-table.wenzhixin.net.cn/examples/#server-side)'s server side pagination to show some content. Several cells can be inplace edited with django-inplaceedit. Everything works when loading the table as usual, but not with bootstrap-table's ajax calls.

bootstrap-table allows to add ajaxOptions to its ajax calls, so, do you have any function that I should call after loading new content to my table in order to activate inplace editions?

Thanks,
Hector.

**Comment by ajendrex** [comment]
Hello,

I'm using [bootstrap-table](http://bootstrap-table.wenzhixin.net.cn/examples/#server-side)'s server side pagination to show some content. Several cells can be inplace edited with django-inplaceedit. Everything works when loading the table as usual, but not with bootstrap-table's ajax calls.

bootstrap-table allows to add ajaxOptions to its ajax calls, so, do you have any function that I should call after loading new content to my table in order to activate inplace editions?

Thanks,
H.

**Comment by ajendrex** [comment]
I now realized that even with static data, but using the pagination feature of bootstrap-table, the inplaceedit functionality is lost. I would appreciate any insight on what should I do to "refresh" the html page so that inplaceedit forms get activated again.

Best regards,
Hector.

**Comment by goinnn** [comment]
I'm sorry I don't know bootstrap-table.

**Comment by Zorig** [comment]
Hello, @goinnn I got exact same problem exact not bootstrap-table just a common Ajax call. How to achieve make it editable after ajax submit without refresh?
