### ISSUE TITLE
How to use an external control to enable inplaceedit?

### ISSUE THREAD

**Issue by shumbashi** [django-inplaceedit/django-inplaceedit#75]
How can I use an external control, e.g. a link, to enable inaplceedit for the closest editable field.

An example for what I mean would be how facebook and google plus does "Edit Post".

**Comment by cericoda** [comment]
HI not sure if it can be done using django-inplaceedit but I used a bit of jquery to do this, placing an icon to the right of the item, and using jquery.prev().
In my case I use click to activate, so that clicking the icon clicks the control:-
```
{% inplace_edit "object.name" %}
<a href="#" class="next_to_inplace_edit" title="click to edit"><i class="icon-pencil"></i> </a>
<script>
    $(".next_to_inplace_edit").click(function(){
        $(".next_to_inplace_edit").prev().click(); 
        return false;
        }
    );
</script>
```
Not very neat but works for me

**Comment by goinnn** [comment]
Solved :-)
