### ISSUE TITLE
model_name issues

### ISSUE THREAD

**Issue by u8sand** [django-inplaceedit/django-inplaceedit#77]
I experienced the error below, clearly--the module_name (now renamed as model_name following patch https://github.com/django-inplaceedit/django-inplaceedit/pull/72/files) is problematic. I've fixed the issue by replacing `self.model._meta.model_name` with `self.model._meta.model_name.split('_')[0]`. This is a quick and ugly fix, any particular reason why this is happening? Might it have something to do with my using raw QuerySets?

	Environment:

	Request Method: GET
	Request URL: http://localhost:8000/inplaceeditform/get_field/?app_label=manager&filters_to_show=markdown&field_name=publications&module_name=faculty_deferred_biography_degree_description_emca1174f154e22436e279761390b161ec&view=edit&obj_id=1&can_auto_save=1&loads=markdown_deux_tags&__widget_font_size=16px&__widget_height=304px&__widget_width=1235px

	Django Version: 1.8.3
	Python Version: 3.4.3
	Installed Applications:
	('django.contrib.admin',
	 'django.contrib.auth',
	 'django.contrib.contenttypes',
	 'django.contrib.sessions',
	 'django.contrib.messages',
	 'django.contrib.staticfiles',
	 'markdown_deux',
	 'pagedown',
	 'inplaceeditform',
	 'manager')
	Installed Middleware:
	('django.contrib.sessions.middleware.SessionMiddleware',
	 'django.middleware.common.CommonMiddleware',
	 'django.middleware.csrf.CsrfViewMiddleware',
	 'django.contrib.auth.middleware.AuthenticationMiddleware',
	 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	 'django.contrib.messages.middleware.MessageMiddleware',
	 'django.middleware.clickjacking.XFrameOptionsMiddleware',
	 'django.middleware.security.SecurityMiddleware')

	Traceback:
	File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
	  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
	File "/home/u8sand/.local/lib/python3.4/site-packages/django_inplaceedit-1.3.0-py3.4.egg/inplaceeditform/views.py" in get_field
	  68.     adaptor = _get_adaptor(request, 'GET')
	File "/home/u8sand/.local/lib/python3.4/site-packages/django_inplaceedit-1.3.0-py3.4.egg/inplaceeditform/views.py" in _get_adaptor
	  91.                                           model=module_name)
	File "/usr/lib/python3.4/site-packages/django/db/models/manager.py" in manager_method
	  127.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
	File "/usr/lib/python3.4/site-packages/django/db/models/query.py" in get
	  334.                 self.model._meta.object_name

	Exception Type: DoesNotExist at /inplaceeditform/get_field/
	Exception Value: ContentType matching query does not exist.

**Comment by goinnn** [comment]
Fixed here 9fcdff3fe0b724869ec09476a9aea566de48bab9
