### ISSUE TITLE
Deprecated model_name

### ISSUE THREAD

**Issue by Colleoni** [django-inplaceedit/django-inplaceedit#83]
Hi,

Thank you very much for your work. I just want to tell you that I have found some problem with Django 1.8. In files: perms.py and fields.py you have used obj.__class__._meta.model_name which has been deprecated and substituted by "module_name" (https://code.djangoproject.com/ticket/19689) I think you may consider to update your code.

Again, thank you very much

Luca

**Comment by goinnn** [comment]
Done:

https://github.com/django-inplaceedit/django-inplaceedit/blob/master/inplaceeditform/perms.py#L34

I will do a new pypi version soon :-)

**Comment by Colleoni** [comment]
wow that is a super fast answer:) thank you very much
