### ISSUE TITLE
 installing django-inplaceedit [jenkins]

### ISSUE THREAD

**Issue by shimaacube** [django-inplaceedit/django-inplaceedit#84]
Hi, i'm trying to install the package  on jenkins .
I get this error msg:

  Downloading django-inplaceedit-1.4.1.tar.gz (51kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-u6fk3rkz/django-inplaceedit/setup.py", line 30, in <module>
        long_description=(read('README.rst') + '\n\n' + read('CHANGES.rst')),
      File "/tmp/pip-build-u6fk3rkz/django-inplaceedit/setup.py", line 22, in read
        return open(os.path.join(os.path.dirname(**file**), *rnames)).read()
      File "<http://example.com/job/assessment/ws/.tox/py34/lib/python3.4/encodings/ascii.py",> line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 709: ordinal not in range(128)

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u6fk3rkz/django-inplaceedit

**note** : when i install this package local , it seems ok >> no problems happen.

**Comment by goinnn** [comment]
Hi @shimaacube , I suppose there is a problem with some unicode character (e.g.:"Jón Levy"). Please, could you reproduce the error manually? I can do (in a virtualenv):

```
git clone git@github.com:django-inplaceedit/django-inplaceedit.git
cd django-inplaceedit
python setup install
```

Or

```
pip install django-inplaceedit
```

without a problem

**Comment by shimaacube** [comment]
thanks , but I remove inplaceedit app from requirments.txt and put it in tox.ini as i put tox in configuration of jenkins and ( tox make virtualenv ) , still the same error !

**Comment by goinnn** [comment]
Please could you test it manually? I need to see the error in my machine for to fix it

**Comment by arunpersaud** [comment]
I think it's a python3 error (I'm getting the same). Lots of places on github have this, one possible fix:

https://github.com/soravux/deap/commit/0424dc6b7a0489fa5cbb9d0482326745b6176c27

more at:

https://github.com/search?q=%22UnicodeDecodeError%3A+%27ascii%27+codec+can%27t+decode+byte%22++setup.py&ref=searchresults&state=closed&type=Issues&utf8=%E2%9C%93

**Comment by goinnn** [comment]
```
virtualenv-3.4 vpython3
source vpython3/bin/activate
 pip3 install git+https://github.com/django-inplaceedit/django-inplaceedit.git

Collecting git+https://github.com/django-inplaceedit/django-inplaceedit.git                                                                                                                                                                                                    
  Cloning https://github.com/django-inplaceedit/django-inplaceedit.git to ./pip-oab02nrf-build                                                                                                                                                                                 
  Installing collected packages: django-inplaceedit                                                                                                                                                                                                                              
  Running setup.py install for django-inplaceedit                                                                                                                                                                                                                              
  Successfully installed django-inplaceedit-1.4.1 
```

I'm sorry, If you want that I fix this error, you should say me how I can see it

**Comment by arunpersaud** [comment]
sorry for the long delay. I can reproduce it on my computer with 

`LC_ALL="C" python3 setup.py build`

I get the same on the build server for opensuse when trying to package the module for python3.

**Comment by pablopda** [comment]
I Had the same error.
Installling gives this error: 
(previous I made git clone https://github.com/django-inplaceedit/django-inplaceedit.git)

```
python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    long_description=(read('README.rst') + '\n\n' + read('CHANGES.rst')),
  File "setup.py", line 22, in read
    return open(os.path.join(os.path.dirname(__file__), *rnames)).read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 709: ordinal not in range(128)
```

Is some symbol in CHANGES.rst. 
I think the problem is on line 24 there is:    \* `Jón Levy <https://github.com/busla>`_
The 'ó' is UTF character and the setup is using ASCII to read the file.

**Comment by pablopda** [comment]
I pushed the patch (reading these files as utf-8) to https://github.com/codingsnippets/django-inplaceedit (more updated copy of inplaceedit)
