### ISSUE TITLE
Not working (v-1.4.1) in Firefox

### ISSUE THREAD

**Issue by sonus21** [django-inplaceedit/django-inplaceedit#86]
I have added all the required configuration in template. It seems that it's not working in firefox where as working in chrome.  Any body is having similar problem ?

**Comment by goinnn** [comment]
Works on my machine, could you test if the testing project works on your machine?

What is the error? Could you see the js console?

**Comment by sonus21** [comment]
Can explain little bit what is testint ? I am new to this editor.

**Comment by sonus21** [comment]
There is no error.Yeah I can see console.

**Comment by goinnn** [comment]
So, if there is no error, django-inplaceedit works in firefox. I suppose you have a problem, error or incompatible library in your project.

**Comment by sonus21** [comment]
But it's working in chrome. how it's possible ?

**Comment by goinnn** [comment]
It is the magic of the browsers
